services:
    serverpunt:
        build:
            context: .
            dockerfile: ./dockerfile
        restart: always
        hostname: serverpunt.com
        env_file:
            - ./.env
        container_name: serverpunt
        ports:
            - "3012:3000"
        dns:
            - 8.8.8.8
            - 1.1.1.1
